### ISSUE TITLE
trie to buld on Manjaro(arch linux) linux fail

### ISSUE THREAD

**Issue by Sacrefice** [AdrienTD/wkbre2#1]
Halow,

have tried to build this on Manjaro(arch linux), and got error:

> g++ -c NNSearch.cpp -o NNSearch.o -std=c++17 -I../inc -O3 -w `sdl2-config --cflags` -Dstrcpy_s=strcpy -D_stricmp=strcasecmp -Dsprintf_s=sprintf -Dstrcmpi=strcasecmp
> NNSearch.cpp: In Elementfunktion »PrgGameObject* NNSearch<Program, PrgGameObject>::next()«:
> NNSearch.cpp:31:71: Fehler: expected primary-expression before »>« token
>    31 |                      PrgGameObject* obj = vec[it++].getFrom<Program>();
>       |                                                                    ^
> 
> NNSearch.cpp:31:73: Fehler: expected primary-expression before »)« token
>    31 |                      PrgGameObject* obj = vec[it++].getFrom<Program>();
>       |                                                                      ^
> 
> make: *** [../Makefile:24: NNSearch.o] Fehler 1

thanks for your love for this game xd

**Comment by AdrienTD** [comment]
Hello!

Yeah, I haven't tested on Linux for a while, so it's very likely that Linux support got broken in the latest commits.

I do wonder why in your log you have "vec[it++].getFrom()" without its template parameter (should be "vec[it++].getFrom\<Program\>()"). Maybe it's just g++ not displaying the line correctly 🤷 . (P.S. It seems that the \< \> characters make things disappear in Markdown, that's probably why I couldn't see it.)

I suggest to check out the [linux-port branch](https://github.com/AdrienTD/wkbre2/tree/linux-port) and try compiling from this version instead, since it should at least compile on Linux (I have tested on some old Ubuntu version), even though you wouldn't have the latest features.

Note that when I tested on Linux, it wasn't transitioned to C++17 yet, so when going to the linux-port branch you will probably have to disable the C++17 mode.

If I have time, I will look if I can fix the code for Linux, this time with a more recent distribution, and check again for better building instructions, because I'm aware they are just bad.

**Comment by AdrienTD** [comment]
Ok, actually in the linux-port you might still need C++17 because I added some C++17 features in few places, my bad.

I just took a look, and got the same error (on Ubuntu 18.04).

I researched, and the problem was because I had to add the `template` keyword to call the template method `getFrom`:
` 	PrgGameObject* obj = vec[it++].template getFrom<Program>();`

Note that I discovered other errors as well, if I have time I will see if I can commit a fix.

**Comment by AdrienTD** [comment]
I just pushed a commit containing some fixes for building on Linux, as well as updated the Makefile to build the new files that have been added since I last worked on the Linux port.

It should hopefully compile, but I couldn't test if the build works, because I only have one VM of Lubuntu 18.04 on my PC right now that has some old compiler and OpenGL 3 didn't work for some reason.

I hope it does work, please tell me if you still have issues.

**Comment by Sacrefice** [comment]
some new errors to play xd

```
g++ -c ParticleContainer.cpp -o ParticleContainer.o -std=c++17 -I../inc -O3 -w `sdl2-config --cflags` -Dstrcpy_s=strcpy -D_stricmp=strcasecmp -Dsprintf_s=sprintf -Dstrcmpi=strcasecmp
In Datei, eingebunden von ParticleContainer.cpp:5:
ParticleContainer.h:19:9: Fehler: »uint32_t« bezeichnet keinen Typ
   19 |         uint32_t objid;
      |         ^~~~~~~~
ParticleContainer.h:10:1: Anmerkung: »uint32_t« is defined in header »<cstdint>«; did you forget to »#include <cstdint>«?
    9 | #include "util/vecmat.h"
  +++ |+#include <cstdint>
   10 |
ParticleContainer.h:23:9: Fehler: »uint32_t« bezeichnet keinen Typ
   23 |         uint32_t getColor(float time);
      |         ^~~~~~~~
ParticleContainer.h:23:9: Anmerkung: »uint32_t« is defined in header »<cstdint>«; did you forget to »#include <cstdint>«?
ParticleContainer.h:36:18: Fehler: »uint32_t« wurde in diesem Gültigkeitsbereich nicht definiert
   36 |         std::map<uint32_t, Trail> trails;
      |                  ^~~~~~~~
ParticleContainer.h:36:18: Anmerkung: »uint32_t« is defined in header »<cstdint>«; did you forget to »#include <cstdint>«?
ParticleContainer.h:36:33: Fehler: Templateargument 1 ist ungültig
   36 |         std::map<uint32_t, Trail> trails;
      |                                 ^
ParticleContainer.h:36:33: Fehler: Templateargument 3 ist ungültig
ParticleContainer.h:36:33: Fehler: Templateargument 4 ist ungültig
ParticleContainer.h:40:72: Fehler: »uint32_t« wurde nicht deklariert
   40 |         void generate(ParticleSystem* system, const Vector3& position, uint32_t objid, float prevTime, float nextTime);
      |                                                                        ^~~~~~~~
ParticleContainer.h:41:53: Fehler: »uint32_t« wurde nicht deklariert
   41 |         void generateTrail(const Vector3& position, uint32_t objid, float prevTime, float nextTime);
      |                                                     ^~~~~~~~
ParticleContainer.cpp:19:10: Fehler: keine Deklaration passt zu »uint32_t Particle::getColor(float)«
   19 | uint32_t Particle::getColor(float time)
      |          ^~~~~~~~
ParticleContainer.cpp:19:10: Anmerkung: keine Funktionen namens »uint32_t Particle::getColor(float)«
In Datei, eingebunden von ParticleContainer.cpp:5:
ParticleContainer.h:13:8: Anmerkung: »struct Particle« hier definiert
   13 | struct Particle
      |        ^~~~~~~~
ParticleContainer.cpp:36:6: Fehler: keine Deklaration passt zu »void ParticleContainer::generate(ParticleSystem*, const Vector3&, uint32_t, float, float)«
   36 | void ParticleContainer::generate(ParticleSystem* system, const Vector3& position, uint32_t objid, float prevTime, float nextTime) {
      |      ^~~~~~~~~~~~~~~~~
In Datei, eingebunden von ParticleContainer.cpp:5:
ParticleContainer.h:40:14: Anmerkung: Kandidat ist: »void ParticleContainer::generate(ParticleSystem*, const Vector3&, int, float, float)«
   40 |         void generate(ParticleSystem* system, const Vector3& position, uint32_t objid, float prevTime, float nextTime);
      |              ^~~~~~~~
ParticleContainer.h:26:8: Anmerkung: »struct ParticleContainer« hier definiert
   26 | struct ParticleContainer {
      |        ^~~~~~~~~~~~~~~~~
ParticleContainer.cpp:60:6: Fehler: keine Deklaration passt zu »void ParticleContainer::generateTrail(const Vector3&, uint32_t, float, float)«
   60 | void ParticleContainer::generateTrail(const Vector3& position, uint32_t objid, float prevTime, float nextTime)
      |      ^~~~~~~~~~~~~~~~~
In Datei, eingebunden von ParticleContainer.cpp:5:
ParticleContainer.h:41:14: Anmerkung: Kandidat ist: »void ParticleContainer::generateTrail(const Vector3&, int, float, float)«
   41 |         void generateTrail(const Vector3& position, uint32_t objid, float prevTime, float nextTime);
      |              ^~~~~~~~~~~~~
ParticleContainer.h:26:8: Anmerkung: »struct ParticleContainer« hier definiert
   26 | struct ParticleContainer {
      |        ^~~~~~~~~~~~~~~~~
ParticleContainer.cpp: In Elementfunktion »void ParticleContainer::update(float)«:
ParticleContainer.cpp:78:33: Fehler: Abfrage des Elementes »begin« in »((ParticleContainer*)this)->ParticleContainer::trails«, das vom Nicht-Klassentyp »int« ist
   78 |         for (auto next = trails.begin(); next != trails.end();) {
      |                                 ^~~~~
ParticleContainer.cpp:78:57: Fehler: Abfrage des Elementes »end« in »((ParticleContainer*)this)->ParticleContainer::trails«, das vom Nicht-Klassentyp »int« ist
   78 |         for (auto next = trails.begin(); next != trails.end();) {
      |                                                         ^~~
ParticleContainer.cpp:82:32: Fehler: Abfrage des Elementes »erase« in »((ParticleContainer*)this)->ParticleContainer::trails«, das vom Nicht-Klassentyp »int« ist
   82 |                         trails.erase(it);
      |                                ^~~~~
make: *** [../Makefile:24: ParticleContainer.o] Fehler 1

```
seems like a missing marking at uint32_t

**Comment by AdrienTD** [comment]
Yeah... you will need to add `#include <cstdint>` at the beginning of ParticleContainer.h

I guess I will have to test with the latest compiler version, since they tend to become more and more strict in the standard headers you need to include.

**Comment by Sacrefice** [comment]
i have tested it and the next error seems to be a missing file

```
gfx/bitmap.cpp:12:10: schwerwiegender Fehler: stb_image_resize.h: Datei oder Verzeichnis nicht gefunden
   12 | #include <stb_image_resize.h>
      |          ^~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
make: *** [../Makefile:24: gfx/bitmap.o] Fehler 1
```

**Comment by Sacrefice** [comment]
i have installed a stb pace from aur, what got mee the files /usr/include/stb_image_resize.h, but nothing change.
after i change the line in bitmap.cpp too "stb_image_resize.h" and  the file in the program kopiet have, the construction was successful.
(have no idea how c++ work i am a pure hoby python Boy) 

Ps: my bad, have overseen the stb part in the manuel xd

**Comment by AdrienTD** [comment]
Great!

I know the building process on Linux is complicated right now, and I hope in the future I can make the process easier (like by making it use CMake instead of the Makefile, even though I once tried and had trouble doing so, and vcpkg doesn't seem to properly work on Linux for certain packages).

I mostly work on Windows with Visual Studio 2019, so it can happen that some changes easily break compatibility with Linux.
